#pragma once

enum Error
{
    ERR_OK,
    ERR_FAILED,
    ERR_FILE_EOF,
    ERR_FILE_NOT_FOUND,
    ERR_FILE_CANT_OPEN,
    ERR_INVALID_PARAMETER,
    ERR_ALREADY_EXISTS,
    ERR_CANT_CREATE,
    ERR_MAX,
};